[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ['cdylib']
[dependencies]
futures = "0.3.25"
wasi = "0.11.0"
wasm-bindgen = "0.2.54"
